#define _FS_READONLY 0
#define _USE_STRFUNC 1
#define _USE_LFN 1
#define _MAX_LFN 255
#define _FS_RPATH 0
#define _VOLUMES 1
#define _MAX_SS 512
#define _NORTC_MON 1
#define _NORTC_MDAY 1
#define _NORTC_YEAR 2015